1. Membuat Tensor

In [10]:
import numpy as np

a = np.array([[[23, 50], [7, 12]],
    [[57, 67], [99, 43]],
    [[75, 21], [57, 12]],
    [[87, 26], [18, 84]],])

a

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

2. Melakukan Perkalian Terhadap Matrix

In [11]:
b = np.array([[23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]])

c = np.array([17, 12, 19])

print(b)
print('')
print(c)
print('')
print(b @ c)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

[17 12 19]

[1352 2334 3635]


3. Melakukan Transpose, hitung determinan, dan inverse terhadap matrix.

In [12]:
d = np.array([[23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]])

d

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [13]:
#transpose
d.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [14]:
#hitung determinant
np.linalg.det(d)

131344.0000000002

In [15]:
#Inverse
np.linalg.inv(d)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])