In [2]:
import numpy as np

In [4]:
a = np.array([[1, -1], [6, 4]])
a

array([[ 1, -1],
       [ 6,  4]])

In [5]:
b = np.array ([1, 3])
b

array([1, 3])

In [7]:
hasil = a @ b / b
hasil

array([-2.,  6.])

[1, 3] bukanlah eigen-vector dari [[1, 1], [6, 4]]